version: '3.9'

services:

  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - 3306:3306

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_NAME=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE${MYSQL_NAME}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=mysqldb
    depends_on:
      - mysqldb

volumes:
  mysql:
  mysql_config:
